# Site settings
title: 无人区科技
email: sales@nomanland.tech
description: >
  本公司致力于3GPP R16场景的实现，
  提供可商用的5G产品，具体请见产品介绍。
lang: zh-CN

baseurl: "/jekyll-doc-theme" # the subpath of your site, e.g. /blog/
url: https://www.opendc.cn # the base hostname & protocol for your site
git_address: https://github.com/jiyif11/web
git_edit_address: https://github.com/jiyif11/web/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
